en_model_name: "openai/whisper-medium"
vi_model_name: ""
sampling_rate: 16000 # read carefully which sampling rate model is  trained with
device: "cpu"
audio_path: "/mnt/c/Users/ASUS/Documents/Capstone project sp23/audio" # for evaluation
caption_path: "../../data/captionData.json"
caption_json: True
chunk_lenght_s: 30 # in seconds
output_dir: "applications/data/output"